language: node_js
node_js:
- node
install:
- npm install -g travis-ci-cloudfront-invalidation
- npm install
cache:
  directories:
  - node_modules
env:
  global:
  - secure: bH7Dh4Ovqdw3c+J9XsB+42LmTQTQMJkRMY397lkJ4Go49ytq2+10laBpaC0YrQuj24iUn84YCCiPQHT/CxRhzRHUAEYV57WE5oL4El5uXqH4BVa2Vo/jtyw0uh901H5OWU3UEyTgehhCOyXPIwRYTSLcpENR8nkkC2Qf8PBnuIlxSymQBbNtBPv6Gm4IWFJ6+YBNVUze0uh2662YQ6a/REjFMRLTFDtdkkIF632Qbduog6aYS17iIVIPRrD+A3cB0lTutdU+SakAzSyDQb2/ygexnjS5xNvxQGS0TFFpBVbsrhFKgG59Ttx9KBSD4sW6tN6H6floUpnXUj6V7lNgaKcjxJvuX2UEhH83uiG6kPA7Trf2Dm7JBBLkyWapo8a0FtjFbZwc5w40IH5/8MCP2fCdrlJYmrNIrk0C/DUK2NYm+ZmS0Zh/R71tyG8DhQ1LsD0j9mMhxDKOt55X0CGYINV/rkn12KPpgCjb6ZzDdrUknAEzczOMDZ3TNr85f+FkTDt+JkPMBdZG9vKqMpMDl7+RHk4K9t7+HFjjaghSRvI4jVyZ96Tt509+yV5PIlMsf+HgKpP/WxE+XoYWYOkbPyx59Fuun5Wn2qU0H919Mah1f6+UnbErCvPdK5AXHitSmRZDUZOLySP2JvcG66RLPNAUhPISgmaS+h2S0gHbogs=
  - secure: kP1YpF5UyV9Qwv0QqnkYMV3+CAzd/l1+cThLEbBq1yDKv0bJFxBHHzcQItWPAfHeF+qbGInYObPSKLNBNvh445XdiJ1ilTdwV7mc1SxBeAW2h/M/y3/fcET0pu5dh7kiqoGjOTNw6wuY35T1xIoBT62eWK34Z6L8PkS3I0RyEsRpkPtm3s2NHsurAxQZdC5wL4c2JJJ4Jmo1mn3lMDfoEPLNtyfsHSGsAnXZLFlhFtKQbmXT5qIMocMxcPoBOnYUiQ+u9LtHFZUIOIVtdMFOsAW5XmcuJDV2hlJoi16gjhDhBi1YBsE4g1XDYHIVQfRO5Z1FVcmRu7UTLmx+8aGlLMLguM872FCKXBpo70ZEXzehjDe68KrbThTHvSvfUhJILXQvrn9b+IpWidbA3AQlnJLrD7e5cGMwFznr/5x3oMEHYsUhoMjjFZJLXzuB4SXrlj8Un4HfUZUybp2nEbOwh5SXl2gfYfmL8YWjXPUIl2UgU713KVWwyyz1OOUO+UxWdfW0gbPccNqvj58hIGt92v3eBI6oVu/zSoFZan4mVTr+4nclckwzeYAqGGaK6Q8z9G4MxO/pmUpYe4BBRww+8PlEXvdv/hIHrfoNs0TgzjfA+xwYRVLkYB6udrrk4xIAbs7d05ZEteldK8x6G5wPaeA5T+cePrzLW43qZryIA9U=
  - secure: mZOKg175u/c6tbkeaFNJVaXhnqVn9qmys8BxaFo89QvgABW5cF6Do8HC+ojcDCIZX+wSy8XzTGtG3EJWOgzrVMNNiRd1djhh4XaPf+PPyjb9tC9HZ35jZvM3yd6Op1wruB8AGJYKNLztAEjbflKzo8q0XlqZubJpa5TdH2SnNC4b7n+b5wP7q0PTN6hmewtv+FaRqEK/dqxrx8pRcpGckCWOe6g7dQhz41jffgZ8/fNx23rIUhgedpASmi7vojwflodw6XriseHvAgNZUEHy3sUkoxMI90X7N4dJBZfiJ0Mgi9JfZGlxXj15bGJwf4mV5nOknbpXJ0nW1qogcuIlAwW5zGQb2LJqq5acBkNhlhcxl6ytCbq20PymIbBLb0UbqyS8QtPq8ZJ/1DenmobH/qiB6tB07u1tUu+WFyszwWMDAl78HPaUEHgp71Jt7iqHamkonjhEmxcMpJZlfrGceNVfFWXztjFmncHDyoVglGicaWOVX+iS7A9elK4vVugyEpby5p20xiSHPlTsQ4x5OH74kchBQt+BtPF4Q9+pVruCCKBZbxi2cpFHr1+i2DNsLNr15clSQ8XegArZwR3jvd92gjAs1NqUtgUfJ4CQSEcAuJbpSZ2dymGiQiTGY7PJAOLAjd4BnfZsoCDM2M/QiTIVFtmNYj2eEey3R3fipoY=
  - secure: MNE1rPEc33l1NYUSKv3cQhLci3lYu6+VOiiMvYlVV9Z+0bYN/kLYu/X/Dp8ie6e/JygXN6NMlgkljnDbWGadXm9XUn8F3dd1DOjFZK+yttIEHuLu/hkjYdFI1poMB1ODsK5b/IcbzwOmNj4e2XmSSyCIVggWUcgCl3Eid9hPeeoy/TJiq5HKl9+WKksAjY6WUZH4QWLfeG5WgUbjBj/yu7Usc7VscHtSiThKGVcr4svUHEui91J6DzvyVI/RMX4Gxx+RXBLRqLmjCy23Vt9JSshxEUmDVuDBZRrEiGrEB8mtzmwOHGb79WcD9AztVv8QFUxc7zP8xVUp5rAO8zpzQ3kvYpus97H35i4zYP8LDDAIZ579ofriUQDJIMXUVMfUpURYpB07FfTtuAMQyox+j5Kk9CLiXovJLR/Pmqs49zcVgzt2JwqilkCiQio12N6ny1wszJ3sY42zETPMXMmLffCMtgMoIrwD9YMKfOKW5Zbp1i3KglLSVwvFyE6IFq4kvaHLcS3v9EGf191mcJy3iBnSDtIJ1fUrAe7TXE3DHnwFErSXiwdAWQnqeVAqVWolENH9VoEmG/pdebOT6el94puCji1oTeW0piiE+nXAW6o+gQHJPDhQN3CEh4lvz+38AryU069OzqX7TNBpurzeVtbSMFbhf5g8Ym9nqAPER3c=
  - secure: Rt+3bRQQVB9okEkxk/bk9hTHnBzoWPPXV/KpYadK9ETK+LfT4jfGeNFIZnPL9j7TuswA1cR8iYxSNHQqlm55JRukWkWFSWwjxqYV/+fsCPFY38TFECMauuz1eOJ7O9XRynJsa6iY2a68eatcdqJzQ30OYu9qhcOUqgi2wBYeUYMGJHMKL18wWLfKYJVbkUm766CQPgKVBSkSK2qeAvjmSMYLSvx5hP52gKgsuAoMcAo7gZvooxuuftwt5/PGXWnH3NaUPo7KYr0yXqOu8KtKKc03a2/cF03oS/Wc7v5JG2QNGeo4jqRF/ivD5EX1JrbwMFDa5QO7m1oSaPSPq6b9I1F8Iw35erxUBwFAD72az1BGJp9WtwnyA0l//VdwubsR8Y4yj0l6G4hQ+vw/ymsK8R/aPW4fHQZwwQgl6onMnW66ZQ3Y/v9YyEcpqErFRIV27v9xhsqRXt3ofRKBR5gmGTFJGoSR56cud06h8Mhp+L1vLaVa6XGMgj6Bq/phEmT2rG0srMNK28raQi/wRNtUNOC3KpNYENg9BZnKp0ABxRaI8Xb7DJUlpOENeiGN3ClLO1f2ebJu6C25D0xUvpaNMH+JtkMMO7O5gk/J5GgiTFaVWASKkUz8S6GEddaKDdiCAnYzg2AlPBrmCyVS8PGT/5SODrp6qVM1MRNk9rO/xVI=
notifications:
  email: false
  irc:
    use_notice: true
    skip_join: false
    on_success: always
    on_failure: always
    template:
    - "%{author} pushed to the repo %{repository_slug} on the %{branch} branch. %{message}"
    - "======================="
    - "%{commit_message}"
    - "======================="
    - 'Code diff: %{compare_url}'
    - 'Travis build log: %{build_url}'
    channels:
      secure: rTrKHjyK1C28ApTukFzEmNS0tfhO5eH4R1UyDfuxjkEt1b1sVThntK3QrNcinvOEvN37uUhFj8OVUH5zj5EwFEgD6QCq9AJ5vWLDeNGBPcEqCZvr6hLNYvjsKKdJ4TK3wPJoVZS0RkR5XtFPaJ3iaGJu4kzFeiTT8VJtSLc1Zv+jJ1yhLcQJQ91YpDKAD9ILjlABbNTcA8NV8y3zX2dSuCoqBE5F3xXSpsqOpW2rpB3zrc52XybCmD9HAQGCkw4wx0k2HKbnsV/6UCe55qrEULASYNtJgy23fUGXA55rrgmKq94TcbLWCm/nDdXSULXQb12hDQOM6wd8qKQWa7BFi0vYd6N2sMfVGvR7325NBMNl+PBb9g3HyF83GOpknV+4K32uv8DaUUno+Hf9P2o++JQj3RiCPYeSpTkNxp9VZoQCNoDxGJF21jYH8/xu+7snhBxMzQgiqqowICaOKNPP9gKxe3Nv17Sr6zGhjOiSAol8hLcLCPcCUcAsARxizftghcwreZOMzeUEl5S/Mhixz8HML++TThhQn0/s/M7xlUw+zdbZnJbdwm51jZeZXSvYm2eupWK2WI1C9TUCNndqK5cvPgdFzhSTv6JaMoBg/z+v/ScTFEVOwFQKWAVNYZoSuPOsjxiAMB31DaUIa0191bemp5P/WeZCoS9pVn/fOew=
git:
  depth: false
before_deploy:
- npm run prod
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_BUCKET_NAME"
  local-dir: dist
  acl: public_read
  region: eu-west-2
  skip_cleanup: true
  on:
    repo: jamtartley/minions_js
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID
  -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
